
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrdenServiceImplService", targetNamespace = "http://service.tienda.ws.promerica.com/", wsdlLocation = "http://localhost:8080/OrdenServiceImplService/OrdenServiceImpl?wsdl")
public class OrdenServiceImplService
    extends Service
{

    private final static URL ORDENSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDENSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ORDENSERVICEIMPLSERVICE_QNAME = new QName("http://service.tienda.ws.promerica.com/", "OrdenServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/OrdenServiceImplService/OrdenServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDENSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ORDENSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public OrdenServiceImplService() {
        super(__getWsdlLocation(), ORDENSERVICEIMPLSERVICE_QNAME);
    }

    public OrdenServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDENSERVICEIMPLSERVICE_QNAME, features);
    }

    public OrdenServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ORDENSERVICEIMPLSERVICE_QNAME);
    }

    public OrdenServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDENSERVICEIMPLSERVICE_QNAME, features);
    }

    public OrdenServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrdenServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrdenWebService
     */
    @WebEndpoint(name = "OrdenServiceImplPort")
    public OrdenWebService getOrdenServiceImplPort() {
        return super.getPort(new QName("http://service.tienda.ws.promerica.com/", "OrdenServiceImplPort"), OrdenWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrdenWebService
     */
    @WebEndpoint(name = "OrdenServiceImplPort")
    public OrdenWebService getOrdenServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.tienda.ws.promerica.com/", "OrdenServiceImplPort"), OrdenWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDENSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ORDENSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ORDENSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
