
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrdenWebService", targetNamespace = "http://service.tienda.ws.promerica.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrdenWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "borrarOrden", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.BorrarOrden")
    @ResponseWrapper(localName = "borrarOrdenResponse", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.BorrarOrdenResponse")
    @Action(input = "http://service.tienda.ws.promerica.com/OrdenWebService/borrarOrdenRequest", output = "http://service.tienda.ws.promerica.com/OrdenWebService/borrarOrdenResponse")
    public void borrarOrden(
        @WebParam(name = "arg0", targetNamespace = "")
        Orden arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "editarOrden", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.EditarOrden")
    @ResponseWrapper(localName = "editarOrdenResponse", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.EditarOrdenResponse")
    @Action(input = "http://service.tienda.ws.promerica.com/OrdenWebService/editarOrdenRequest", output = "http://service.tienda.ws.promerica.com/OrdenWebService/editarOrdenResponse")
    public void editarOrden(
        @WebParam(name = "arg0", targetNamespace = "")
        Orden arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "crearOrden", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.CrearOrden")
    @ResponseWrapper(localName = "crearOrdenResponse", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.CrearOrdenResponse")
    @Action(input = "http://service.tienda.ws.promerica.com/OrdenWebService/crearOrdenRequest", output = "http://service.tienda.ws.promerica.com/OrdenWebService/crearOrdenResponse")
    public void crearOrden(
        @WebParam(name = "arg0", targetNamespace = "")
        Orden arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns clientews.servicio.Orden
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarOrdenPorId", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.BuscarOrdenPorId")
    @ResponseWrapper(localName = "buscarOrdenPorIdResponse", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.BuscarOrdenPorIdResponse")
    @Action(input = "http://service.tienda.ws.promerica.com/OrdenWebService/buscarOrdenPorIdRequest", output = "http://service.tienda.ws.promerica.com/OrdenWebService/buscarOrdenPorIdResponse")
    public Orden buscarOrdenPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Orden arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clientews.servicio.Orden>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarOrdenes", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.ListarOrdenes")
    @ResponseWrapper(localName = "listarOrdenesResponse", targetNamespace = "http://service.tienda.ws.promerica.com/", className = "clientews.servicio.ListarOrdenesResponse")
    @Action(input = "http://service.tienda.ws.promerica.com/OrdenWebService/listarOrdenesRequest", output = "http://service.tienda.ws.promerica.com/OrdenWebService/listarOrdenesResponse")
    public List<Orden> listarOrdenes();

}
